### ISSUE TITLE
Unicode issues

### ISSUE THREAD

**Issue by msoucy** [msoucy/RepBot#22]
Apparently doing `dd bs=1024 count=1 if=/dev/urandom` into a channel is NOT something that RepBot enjoys.

Input should handle unicode properly...

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/policies.py", line 118, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/usr/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 2413, in dataReceived
    basic.LineReceiver.dataReceived(self, data.replace('\r', ''))
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 564, in dataReceived
    why = self.lineReceived(line)
  File "/usr/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 2421, in lineReceived
    self.handleCommand(command, prefix, params)
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 2465, in handleCommand
    method(prefix, params)
  File "/usr/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 1937, in irc_PRIVMSG
    self.privmsg(user, channel, message)
  File "RepBot.py", line 190, in privmsg

  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0x8f in position 5: invalid start byte
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/policies.py", line 118, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/usr/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 2413, in dataReceived
    basic.LineReceiver.dataReceived(self, data.replace('\r', ''))
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 564, in dataReceived
    why = self.lineReceived(line)
  File "/usr/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 2421, in lineReceived
    self.handleCommand(command, prefix, params)
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 2465, in handleCommand
    method(prefix, params)
  File "/usr/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 1937, in irc_PRIVMSG
    self.privmsg(user, channel, message)
  File "RepBot.py", line 190, in privmsg

  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xda in position 0: invalid continuation byte
```

**Comment by msoucy** [comment]
So, in the basic cases it handles unicode safely...

This will be closed for now, unless/until a rewrite happens where I choose a system that doesn't hate Unicode as much.
